# Generated by Django 5.2 on 2025-08-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appTwo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic", old_name="topic", new_name="topic_name",
        ),
    ]
