# Generated by Django 5.2.5 on 2025-08-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appTwo", "0002_rename_topic_topic_topic_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_mane", models.CharField(max_length=100)),
                ("last_mane", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
