# Generated by Django 5.2.5 on 2025-08-31 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appTwo", "0003_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="first_mane", new_name="first_Name",
        ),
        migrations.RenameField(
            model_name="user", old_name="last_mane", new_name="last_Name",
        ),
    ]
